version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - ./server:/app
    ports:
      - "9096:80"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"